//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.DigitalOffice.UserService.Validation.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LT.DigitalOffice.UserService.Validation.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAAQAAAASCAYAAAB8fn/4AAAMaWlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0jvUoJoUUQkCqISkgCCSXGhKBiVxYVXLuIoqJYEdvqCshaEHtZFHtfLKgo62JBUVTehAR03Ve+d/LNnT//nDntztx7BwDNXq5Eko9qAVAgLpQmRIYyx6SlM0kdAANagAZ/DlyeTMKKj48BUAb7v8v7GwBR9FedFbb+Of5fRYcvkPEAQDIgzuLLeAUQNwOAr+NJpIUAEBW85eRCiQLPhlhXCgOEeKUC5yjxDgXOUuLDAzpJCWyILwOgRuVypTkAaNyDPLOIlwPtaHyG2FXMF4kB0HSCOIgn5PIhVsTuVFAwUYErIbaD+hKIYTzAN+s7mzl/s581ZJ/LzRnCyrwGRC1MJJPkc6f+n6X531KQLx/0YQMbVSiNSlDkD2t4K29itAJTIe4SZ8XGKWoNca+Ir6w7AChFKI9K [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Base64String {
            get {
                return ResourceManager.GetString("Base64String", resourceCulture);
            }
        }
    }
}
